
INSERT INTO FEATURE (ID, DISPLAY_NAME, TECHNICAL_NAME, DESCRIPTION)
VALUES (1, 'my-feature-a', 'my.feature.a', 'feature a');

INSERT INTO FEATURE (ID, DISPLAY_NAME, TECHNICAL_NAME, DESCRIPTION)
VALUES (2, 'my-feature-b', 'my.feature.b', 'feature b');

INSERT INTO FEATURE (ID, DISPLAY_NAME, TECHNICAL_NAME, DESCRIPTION)
VALUES (3, 'my-feature-c', 'my.feature.c', 'feature c');

INSERT INTO FEATURE (ID, DISPLAY_NAME, TECHNICAL_NAME, DESCRIPTION)
VALUES (4, 'my-feature-d', 'my.feature.d', 'feature d');

INSERT INTO CUSTOMER (ID, NAME)
VALUES (1, 'george wiles');

-- contains hypersonic specific date syntax
INSERT INTO CUSTOMER_FEATURE (ID, EXPIRATION_DATE, IS_ACTIVE, IS_INVERTED, CUSTOMER_ID, FEATURE_ID)
VALUES (1,  DATEADD('MONTH', 1, CURRENT_TIMESTAMP), TRUE, TRUE, 1, 1);

INSERT INTO CUSTOMER_FEATURE (ID, EXPIRATION_DATE, IS_ACTIVE, IS_INVERTED, CUSTOMER_ID, FEATURE_ID)
VALUES (2,  DATEADD('MONTH', 2, CURRENT_TIMESTAMP), TRUE, FALSE, 1, 2);

INSERT INTO CUSTOMER_FEATURE (ID, EXPIRATION_DATE, IS_ACTIVE, IS_INVERTED, CUSTOMER_ID, FEATURE_ID)
VALUES (3,  DATEADD('MONTH', 3, CURRENT_TIMESTAMP), TRUE, TRUE, 1, 3);

-- expires this customer feature
INSERT INTO CUSTOMER_FEATURE (ID, EXPIRATION_DATE, IS_ACTIVE, IS_INVERTED, CUSTOMER_ID, FEATURE_ID)
VALUES (4, DATEADD('MONTH', -3, CURRENT_TIMESTAMP), FALSE, TRUE, 1, 4);


