-- src/main/resources/db-schema.sql

CREATE TABLE FEATURE (
    ID INT PRIMARY KEY,
    DISPLAY_NAME VARCHAR(250) DEFAULT NULL,
    TECHNICAL_NAME VARCHAR(250) NOT NULL,
    EXPIRES_ON TIMESTAMP DEFAULT NULL,
    DESCRIPTION VARCHAR(250) NOT NULL
);

INSERT INTO FEATURE (ID, DISPLAY_NAME, TECHNICAL_NAME, EXPIRES_ON, DESCRIPTION) VALUES
(1, 'my-feature-a', 'my.feature.a',  "2024-01-10T12:30:45Z", "a test feature");
